---
name: TypeScript

"on":
  push:
    paths:
      - "**.ts"
      - "package.json"
      - "package-lock.json"

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3.0.0
        with:
          cache: npm
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  style:
    name: Check style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3.0.0
        with:
          cache: npm
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: ./node_modules/.bin/prettier --check "**/*.ts"
