---
name: Markdown

"on":
  push:
    paths:
      - "**.md"

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3.0.0
        with:
          cache: npm
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run markdownlint
        run: ./node_modules/.bin/markdownlint **/*.md --ignore node_modules

  style:
    name: Check style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: prettier
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_options: "--check **/*.md"
